<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.web>
    <!-- nÃ£o controla FastCGI, mas pode ficar -->
    <httpRuntime executionTimeout="600" />
  </system.web>

  <system.webServer>

    <fastCgi>
      <application
        fullPath="D:\taskfy\venv\Scripts\python.exe"
        arguments="D:\taskfy\venv\Lib\site-packages\wfastcgi.py"
        activityTimeout="00:10:00"
        requestTimeout="00:10:00"
        idleTimeout="00:10:00"
        instanceMaxRequests="100000"
        maxInstances="1">
        <environmentVariables>
          <environmentVariable name="DJANGO_SETTINGS_MODULE" value="taskfy.settings" />
          <environmentVariable name="PYTHONPATH" value="D:\taskfy" />
          <environmentVariable name="WSGI_HANDLER" value="django.core.wsgi.get_wsgi_application()" />
          <environmentVariable name="WSGI_LOG" value="D:\taskfy\logs\wfastcgi.log" />
          <environmentVariable name="PYTHONUNBUFFERED" value="1" />

           <!-- APS (Forge) -->
          <environmentVariable name="APS_CLIENT_ID" value="SUA_CLIENT_ID_AQUI" />
          <environmentVariable name="APS_CLIENT_SECRET" value="SUA_CLIENT_SECRET_AQUI" />
          <environmentVariable name="APS_CALLBACK_URL" value="http://192.168.1.2:8080/api/aps/callback" />
          
        </environmentVariables>
      </application>
    </fastCgi>

    <handlers>
      <add name="Django Handler"
           path="*"
           verb="*"
           modules="FastCgiModule"
           scriptProcessor="D:\taskfy\venv\Scripts\python.exe|D:\taskfy\venv\Lib\site-packages\wfastcgi.py"
           resourceType="Unspecified" />
    </handlers>

    <httpErrors existingResponse="PassThrough" />
  </system.webServer>
</configuration>
